FROM alpine:3.23

RUN apk add --no-cache tzdata bash busybox-extras 




#docker build . --build-arg "HTTP_PROXY=http://127.0.0.1:1087/" --build-arg "HTTPS_PROXY=http://127.0.0.1:1087/"  --network host -t alpine:1


# docker build . -t afreto/alpine:1

# docker push afreto/alpine:1
