version: '3'
services:
  frps:
    container_name: frps
    image: snowdreamtech/frps
    volumes: 
      - /etc/frp/:/etc/frp
    restart: always
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 1m
    

    