test:
	docker build -f ./Dockerfile  -t registry.cn-hangzhou.aliyuncs.com/kiwi0325/caddy:test .
	docker push registry.cn-hangzhou.aliyuncs.com/kiwi0325/caddy:test
	docker rmi registry.cn-hangzhou.aliyuncs.com/kiwi0325/caddy:test


.PHONY: test
