version: '3'

services:
    melody:
        image: foamzou/melody
        container_name: melody
        ports:
          - '10122:5566'
        volumes: 
          - /etc/melody:/app/backend/.profile
        restart: unless-stopped
        