version: '3'

services:
    rsshub:
        image: diygod/rsshub
        container_name: rsshub
        restart: always
        ports:
            - '10118:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://default:qpzm2745@redis:home.pi.afreto.top:10117/'
            # PUPPETEER_WS_ENDPOINT: 'ws://browserless:10119'
        # depends_on:
            # - redis
            # - browserless

    # browserless:
    #     image: browserless/chrome
    #     container_name: rsshub_browserless
    #     restart: always
    #     ports:
    #         - 10119:3000
    #     ulimits:
    #       core:
    #         hard: 0
    #         soft: 0

    # redis:
    #     image: redis:alpine
    #     restart: always
    #     volumes:
    #         - /data/rsshub:/data

