version: '3'

services:
  container_name: youtube_dl_flask
  youtube-dl:
  image: recodeuk/youtube-dl-flask
  ports:
    - 10117:80
  volumes:
  - /data/disk1/emby/share1:/youtube-dl
  restart: always
