version: "3"

services:
  freshrss:
    container_name: prometheus
    image: prom/prometheus
    environment: 
      - TZ=Asia/Shanghai
      # - CRON_MIN=31
    ports:
      - 9090:9090
    restart: unless-stopped
    # volumes:
      # - /data/freshrss/data:/var/www/FreshRSS/data
      # - /data/freshrss/ext:/var/www/FreshRSS/extensions
      # - /data/freshrss/config:/config
    logging:
      driver: json-file
      options:
        max-size: 1m
