version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    environment: 
      - TZ=Asia/Shanghai
      # - CRON_MIN=31
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - /etc/prometheus:/etc/prometheus
      # - /data/freshrss/ext:/var/www/FreshRSS/extensions
      # - /data/freshrss/config:/config
    logging:
      driver: json-file
      options:
        max-size: 1m
