# 使用官方的 Grafana 基础镜像
FROM grafana/grafana:latest

# 设置环境变量（可选）
# ENV GF_SECURITY_ADMIN_USER=admin
# ENV GF_SECURITY_ADMIN_PASSWORD=admin

# 如果需要添加自定义插件，可以在这里安装
# RUN grafana-cli plugins install <plugin-name>

# 如果需要添加自定义配置文件，可以在这里复制
COPY grafana.ini /etc/grafana/grafana.ini

# 暴露 Grafana 默认的端口
EXPOSE 3000

# 启动 Grafana
CMD ["grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini"]