version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.7-management
    volumes:
      - /etc/rabbitmq:/etc/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped