version: '3'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qpzm2745
    ports:
      - "27017:27017"
    volumes:
      - '/data/mongodb/:/data/db'
    restart: unless-stopped
