FROM debian:11
LABEL maintainer="afreto@kong5664546498@gmail.com"
RUN ["apt-get","update"]
#RUN ["apt-get","install","npm","-y"]
#RUN apt install npm -y
#RUN npm install -g yapi-cli --registry https://registry.npm.taobao.org
#CMD [ "yapi","server" ]
# RUN ["apt-get","install","python3","-y"]
# RUN ["apt","install","python3-pip","-y"]
# RUN ["pipe","install","pipenv"]


#docker build . --build-arg "HTTP_PROXY=http://127.0.0.1:1087/" --build-arg "HTTPS_PROXY=http://127.0.0.1:1087/"  --network host -t debian:1
# docker tag debian:1 afreto/debian:1
# docker push afreto/debian:1
