version: '3'
services:
  chrome:
    container_name: checkchan
    image: easychen/checkchan:latest
    volumes:
      - /data/checkchan:/checkchan/data
    environment:
      - "CKC_PASSWD=qpzm2745"
      - "VDEBUG=OFF"
      - "VNC=ON"
      #- "WIN_WIDTH=414"
      #- "WIN_HEIGHT=896"
      #- "XVFB_WHD=500x896x16"
      - "API_KEY=2745"
      - "ERROR_IMAGE=NORMAL" # NONE,NORMAL,FULL
      #- "SNAP_URL_BASE=<开启截图在这里写服务器地址（结尾不用加/），不开留空>..."
      #- "SNAP_FULL=1"
      - "TZ=Asia/Chongqing"
    ports:
      - "10120:5900" 
      - "10121:8080" 
      - "10122:80"
