version: '3'

services:
    redis_test:
        image: redis
        ports: 6379:6479
        volumes: 
            - /etc/redis:/usr/local/etc/redis/
            - /data/redis/data:/data
        restart: unless-stopped
    