version: '3'

services:
    redis:
        container_name: redis
        image: redis
        ports: 
            - 6379:6379
        volumes: 
            - /etc/redis:/usr/local/etc/redis/
            - /data/redis/data:/data
        restart: unless-stopped
    