version: '3'

services:
    redis:
        container_name: redis
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        command: redis-server /etc/redis/redis.conf
        ports: 
            - 6379:6379
        volumes: 
            - /etc/redis:/etc/redis/
            - /data/redis/data:/data
        restart: unless-stopped
    